package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_LOGICO, PARENTESIS_IZQ, PARENTESIS_DER, DESCONOCIDO,OPERADOR_DE_ASIGNACION,REAL, OPERADOR_RELACIONAL
}