package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_LOGICO, PARENTESIS_IZQ, PARENTESIS_DER,
    DESCONOCIDO,OPERADOR_DE_ASIGNACION,REAL, OPERADOR_RELACIONAL,SIMBOLO_DE_CERRAR,SIMBOLO_DE_ABRIR,
    TERMINAL_O_INICIAL,CARACTER,ASIGNACION_PARA_CADENA,PALABRA_RESERVADA_BUCLES,PALABRA_RESERVADA_PARA_CADENA,
    PALABRA_RESERVADA_PARA_ENTERO, PALABRA_RESERVADA_PARA_DECIMAL, PALABRA_RESERVADA_PARA_CARACTER,PALABRA_RESERVADA_PARA_ITERADOR,
    PALABRA_RESERVADA_PARA_DECISION,PALABRA_RESERVADA_PARA_MAIN,PALABRA_RESERVADA_PARA_NOMBRES_VARIABLES,
    PALABRA_RESERVADA_PARA_NOMBRES_METODOS,PALABRA_RESERVADA_PARA_NOMBRES_CLASES, PALABRA_RESERVADA, COMA, DOS_PUNTOS,BOOLEANO,VERDADERO,FALSO,
    OPERADOR_NEGACION,INCREMENTO,DECREMENTO, BLOQUE_COMENTARIO, LINEA_COMENTARIO, INVOCACION

}
